export const seedQuotes = [
  {
    text: `Consider moving to the UAE if you are an entrepreneur looking to minimize your tax burden. The interviewee strongly endorses this, expressing trust and belief in the country's leadership and direction.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=4uFVDpGTHPQ`,
    videoTitle: `Asking Billionaires If They Pay Taxes!`,
    topic: `taxes`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Go for it. Stop stalling, stop waiting, stop self-doubting. People less competent, less creative, less talented than you have made it. Stop hesitating. Just go for it. Jump today.`,
    speakerName: `London Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=mRJN1l_w-Co`,
    videoTitle: `Asking London Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Embarrassment is the most underexplored emotion when it comes to success. You have to go out there and make a fool of yourself, because once you make a fool of yourself, then comes refinement, then comes clarity, then comes confidence.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=npnyOvchXZs`,
    videoTitle: `Asking Billionaires If They Believe In God!`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `I never give up. Never, never, never. You're going to have to kill me.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=dK5bG5ZE3yI`,
    videoTitle: `Asking Billionaires If Getting Rich Was Worth It`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `"Don't sweat the small things, and everything is small," because we can only control today. Furthermore, "don't ever put a limit on God's dreams for your life," as His plans are often much bigger than our own.`,
    speakerName: `Dallas Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=rrDdi0vZn00`,
    videoTitle: `Asking Dallas Billionaires How They Got Rich!`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice, given as a lesson on how to "sell a pen," is that before pitching a product, you must first ask questions to find out if the person actually needs or wants it. You shouldn't waste time trying to sell to someone who isn't in the market for what you're offering.`,
    speakerName: `Miami Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=lU-bh2xPl4Y`,
    videoTitle: `Asking Miami Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The key to success is empathy. Strive to be empathetic and sympathetic every day, because people will ultimately remember how you made them feel, even if they don't remember your name.`,
    speakerName: `Beverly Hill Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=uwh4gWNgb1w`,
    videoTitle: `Asking Beverly Hill Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't sell. Hold. When it comes to real estate, when it comes to anything else, hold. Be patient. Don't worry about the chips you want to take off the table today. Stay in the game. Don't sell your stuff. Don't sell your assets.`,
    speakerName: `Mega Mansion Owners`,
    videoUrl: `https://www.youtube.com/watch?v=E_9nX5ReMcY`,
    videoTitle: `Asking Mega Mansion Owners How They Got Rich!`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Most people fail not because they lack ideas, but because they never start or execute them. The most expensive real estate is in graveyards, where billion-dollar ideas remain buried with those who never took action.`,
    speakerName: `NY Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=DmDeNuTUetE`,
    videoTitle: `Asking NY Billionaires How They Got Rich!`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Take advantage of your life. Don't let your life pass you by, do as much as you can, achieve as much as you can, live it to the fullest, and enjoy the journey. It's not about the destination, enjoy the journey to the fullest. You work hard, you do your best, and you leave the rest on God.`,
    speakerName: `Middle Eastern Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=njD4aqTp0i4`,
    videoTitle: `Asking Middle Eastern Billionaires How They Got Rich!`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Find God, work hard, persevere, and practice discipline. And don't give a f*** what anybody else thinks.`,
    speakerName: `Wealthy Americans`,
    videoUrl: `https://www.youtube.com/watch?v=AUaEd3_JbP8`,
    videoTitle: `Asking Wealthy Americans How They Got Rich! (Palm Beach)`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Keep fighting, keep going, and then do what you want to do.`,
    speakerName: `Hong Kong Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=ITU1TpTwe8w`,
    videoTitle: `Asking Hong Kong Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Leave something valuable behind, whether it's a project or product that positively changes people's lives while generating income. Solve a big problem to create a meaningful legacy.`,
    speakerName: `One of the Richest Men in Dubai`,
    videoUrl: `https://www.youtube.com/watch?v=yUCRSAWh_ls`,
    videoTitle: `Asking One of the Richest Men in Dubai How He Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to find your "Ikigai," a Japanese concept for discovering what is right for you. Build a business or product that combines what makes money, what you are good at, and what helps the world, as this combination is the true secret to ultimate success.`,
    speakerName: `Millionaire Mansion Owners`,
    videoUrl: `https://www.youtube.com/watch?v=Fe7v_SWuhY4`,
    videoTitle: `Asking Millionaire Mansion Owners How They Got RICH`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Play to win and strive to be number one, because 'if you're not number one, nobody cares.' You must at least be 'going for it.'`,
    speakerName: `Wealthy Americans`,
    videoUrl: `https://www.youtube.com/watch?v=z810EM7Q5Mg`,
    videoTitle: `Asking Wealthy Americans How They Got So Rich! (Scottsdale)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Create happiness for yourself and happiness for everyone around you, and you will succeed.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=wOsnxJCy2p8`,
    videoTitle: `Asking Millionaires How They Got Rich! (Silicon Valley)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Everyone experiences failures, but dwelling on them prevents success; instead, focus on past successes to move forward. The ultimate message is to spend as much time as possible with family and rely on faith and family during difficult times.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=hJYkUMV8I_s`,
    videoTitle: `Asking Millionaires How They Got RICH! (Philadelphia)`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Literally every day when you get out of bed, you try to be better than you were yesterday. Doesn't matter how old you are, whether it was physically, improve your relationships or your business. How do we beat yesterday?`,
    speakerName: `Dana White`,
    videoUrl: `https://www.youtube.com/watch?v=ZdUmqGB-XpA`,
    videoTitle: `I Asked Dana White How He Made $500 Million!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Surround yourself by people who have what you want, it's really important. And understand that money does not buy you happiness. Money buys you freedom... just be aware of its value and the dangers of it.`,
    speakerName: `Wall Street Moguls`,
    videoUrl: `https://www.youtube.com/watch?v=AATw4YRFSw8`,
    videoTitle: `Asking Wall Street Moguls How They Got Rich!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Live each day as a life in miniature. Live it on steroids and wake up with gratitude... Live it like you dream it.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=aGrMOowjMag`,
    videoTitle: `I Interviewed 30 Billionaires... Here’s What I Learned`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice shared is the guiding principle "DFSU," which stands for "Don't fuck shit up." This serves as a reminder to avoid self-sabotage and stay on the right track.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=t8FXPpfkxQY`,
    videoTitle: `A 60 Year Old Millionaire Shares What Actually Made Him RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Solve a problem, bet on yourself, and have fun!`,
    speakerName: `Billionaire Women`,
    videoUrl: `https://www.youtube.com/watch?v=2Q2JgVDvHV0`,
    videoTitle: `Asking Billionaire Women How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given in the video is: "Who you associate with is going to determine who you're going to be. If you hang out with losers, you're going to be a loser. If you hang out with millionaires... you're going to be so successful!"`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=nOL-StM6QnU`,
    videoTitle: `Asking Millionaires How They Got RICH! (Chicago)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Live life to the fullest. Live every day like it's your last, and one day you'll be right.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=zN087p7dHN0`,
    videoTitle: `Asking Billionaires How They Got RICH! (Florida)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't let anybody ever stop you from chasing your dreams. Figure out something you're good at, solve a problem, figure out what you stand for, and market your ass off.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=7i0D5OMZzw0`,
    videoTitle: `I Investigated the $1 Trillion Industry Nobody Talks About`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Look for knowledge that you can apply to your lives and don't be afraid to be nervous. Keep pursuing your dreams and finding things that add to your life and others, as true leadership is about serving and helping others be better.`,
    speakerName: `Tom Cruise`,
    videoUrl: `https://www.youtube.com/watch?v=vMcZyzTNoIc`,
    videoTitle: `I Asked Tom Cruise How He Made $600 Million`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If your ambition is to become a billionaire, good luck, but if you have meaningful ambitions, you'll do well. Getting rich is life's biggest booby prize; it is ultimately better to choose to be happy rather than just rich.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=lXitjVjEhEs`,
    videoTitle: `Asking Billionaires How They Got RICH! (Boston)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be proud of the person you look back at in the mirror every single day, because that's the person you got to satisfy. The life you lead is the lesson you teach. If you want to live a life with integrity, resilience, caring, and joy, be that.`,
    speakerName: `Tom Brady`,
    videoUrl: `https://www.youtube.com/watch?v=cTs9SgRk4SI`,
    videoTitle: `I Was the 199th Pick... Now I'm Worth $300M (Tom Brady)`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `One of our values is sales driven but still being profit-smart, but be sales driven.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=n5EmUiLNVjg`,
    videoTitle: `How I Turned $50,000 Into $20 Billion`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Believe in yourself even if others think your ideas are crazy at first. Focus intensely on one specific goal or project for an entire year, dedicating all your free time outside of your regular job to it, and you will be guaranteed to see results.`,
    speakerName: `Adin Ross`,
    videoUrl: `https://www.youtube.com/watch?v=iRgdOE8Fags`,
    videoTitle: `I Asked Adin Ross How He Made $100 Million`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Love doing what you do. Life is too short... You get to live one life. You gotta love every minute.`,
    speakerName: `the RICHEST People in the World`,
    videoUrl: `https://www.youtube.com/watch?v=gBBlX7v0910`,
    videoTitle: `Asking the RICHEST People in the World How They Got RICH!`,
    topic: `lifestyle`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You have to figure out what your special thing is that you know how to do better than 95% of the population. Then figure out how to apply that to a business that needs those skill sets and talents to be successful. Lastly, you need to be super passionate about it so you don't quit when things get long and boring, and you have to enjoy the process.`,
    speakerName: `Wealthy Americans`,
    videoUrl: `https://www.youtube.com/watch?v=TllMBc9YvKk`,
    videoTitle: `Asking Wealthy Americans How They Got Rich!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Sell joy. It's not what you say, it's how you make people feel. You'll never find anything in life as fascinating as another human being; everybody has a story, and if you approach them with open fascination about their life, you'll learn them—and that works in sales too.`,
    speakerName: `Robert Herjavec`,
    videoUrl: `https://www.youtube.com/watch?v=9QTBl0R_cs8`,
    videoTitle: `I Asked Robert Herjavec How He Made $500 Million`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The speaker advises that it is better to give than to receive, explaining that those who give without expecting anything in return build trust and ultimately receive the most help from others. He contrasts this with "takers," whom people naturally tend to be guarded against.`,
    speakerName: `A Billionaire Lawyer`,
    videoUrl: `https://www.youtube.com/watch?v=EF6-Ed2H2cE`,
    videoTitle: `Asking A Billionaire Lawyer How To Make $1,000,000!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You already have everything you need within you, so go deep and work on yourself. Enjoy the journey and the person you become along the way, rather than just focusing on the destination. Don't look for shortcuts; take the detour, because the growth you experience will help you in life.`,
    speakerName: `Millionaire Homeowners`,
    videoUrl: `https://www.youtube.com/watch?v=7Yx6-8nMbkc`,
    videoTitle: `Asking Millionaire Homeowners How They Got Rich`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Recognize the absolute infinite nature of what you could do. You literally can do anything that you choose; it just takes a certain amount of willingness to suffer.`,
    speakerName: `Will Smith`,
    videoUrl: `https://www.youtube.com/watch?v=9iWLPlPFdBY`,
    videoTitle: `I Asked Will Smith How He Made $350 Million`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The interviewee suggests that many people believe the system is rigged because they are missing the "playbook." He encourages them to "open it up" and "run the play."`,
    speakerName: `Politicians`,
    videoUrl: `https://www.youtube.com/watch?v=eEg5ZjFxMmU`,
    videoTitle: `Asking Politicians How They Actually Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The host advises viewers who want direct access to millionaires and personalized mentorship to join his private entrepreneur community, "School of Mentors," by clicking the link in the video's description.`,
    speakerName: `Beverly Hills Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=uUwf3HM_bBg`,
    videoTitle: `Asking Beverly Hills Billionaires How They Got So RICH!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Take a lot of risk, start a business, and build it up to create an immense amount of cash flow and revenue consistently year over year to eventually reach your goals.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=4fOaAGCuuJU`,
    videoTitle: `I Had $78... Now I’m Worth $100 Million`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Life is a team sport, not an individual sport. Pick your team.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=q8u9vs2xjg4`,
    videoTitle: `Meet the Billionaire Who Created LinkedIn (Then Sold It for $26B)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The number one shortcut to success in today's world is mentorship. It's getting in the rooms with and finding the people that you want to be exactly like. The only way to go from point A to point B in your life, career, and business is getting mentored by the most successful people.`,
    speakerName: `Palm Beach Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=gotxAQD0YkE`,
    videoTitle: `Asking Palm Beach Billionaires How They Got So RICH!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final lesson shared at the end of the video is about resilience and readiness in the face of adversity. It is to always "carry your helmet" and be prepared for attacks, while remaining unafraid to tell hard truths, roll up your sleeves, and do the hard work necessary to deliver results.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=9YldQVM4u-I`,
    videoTitle: `How I Turned –$20 Million Into $3.3 Billion`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is to surround yourself with a great team, as you will never achieve massive success by yourself. You must find the right people, gather them around you, and then tackle a significant problem together.`,
    speakerName: `Texan Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=uMXIsDecZ3s`,
    videoTitle: `Asking Texan Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You gotta build it block by block and never stop. In real estate, you're not going to fail if you do your homework and you assert yourself in finding a deal, but you gotta have a plan that makes sense.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=DwrRvp_qsRk`,
    videoTitle: `He Made $500 Million Playing Real Life Monopoly`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is that success comes from a consistent mindset: "It's a whole mindset. If you go to the gym and you're dedicated and you go there every day, you're going to go to work every day too."`,
    speakerName: `Miami’s Millionaire Elite`,
    videoUrl: `https://www.youtube.com/watch?v=8wU_31Wamcw`,
    videoTitle: `I Asked Miami’s Millionaire Elite How They Got Rich`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Everything good in my life is a gift. That's the greatest lesson. I woke up this morning and I opened my eyes and guess what I could do? I could see. And I know how to make myself look, but I don't know how to make myself see.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=GCXhTFKVHkg`,
    videoTitle: `I Was Broke.. Found God.. Now I Make $15M/Year`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Mentorship is the only shortcut to success.`,
    speakerName: `Wall Street Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=bfIJxp9ckKU`,
    videoTitle: `Asking Wall Street Millionaires How To Make $1 Million`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be yourself and be authentic, because people can tell the difference and they value the real deal. Build on what you have by staying true to who you are.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=nswPe9PAgjo`,
    videoTitle: `She Turned $1,000 Into a $66M Empire at 76 Years Old!`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The number one thing I learned is that people better than you will give you permission to become better yourself. While others may tell you to just be humble and grateful, you can be grateful for what you have and still want more.`,
    speakerName: `Bugatti Owners`,
    videoUrl: `https://www.youtube.com/watch?v=_sAyC_CLqzg`,
    videoTitle: `Asking Bugatti Owners How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be diplomatic, never be disrespectful, but put yourselves into their shoes after the deal.`,
    speakerName: `Dubai Supercar Owners`,
    videoUrl: `https://www.youtube.com/watch?v=gZ0RTpQZf8A`,
    videoTitle: `Asking Dubai Supercar Owners How They Got RICH!`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `It's not what you have, it's what you do with what you have. It's not about even working smarter, it's about being more strategic. Go where they don't go... zig when they zag, get creative, and have fun while you're doing it.`,
    speakerName: `Women Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=5E-lydM23gU`,
    videoTitle: `Asking Women Billionaires How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Trust yourself, go for it, and do things you love. The key is to invest—don't just save, but invest in yourself, your health, your mind, and various businesses or markets throughout your life.`,
    speakerName: `Dubai Moguls`,
    videoUrl: `https://www.youtube.com/watch?v=vUumRjZX0n8`,
    videoTitle: `Asking Dubai Moguls How They Got Rich!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The number one thing separating the middle class from wealthy people is having "no limits." Wealthy people believe there is no limit to what they can achieve or earn, and they focus on solving problems and creating solutions to make money, rather than relying on structured jobs or climbing a predetermined corporate ladder.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=QJP9OXmI5_4`,
    videoTitle: `I Was on Food Stamps... Now I Make $100M/Year`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given at the end of the video is to "Let go and let God." The speaker explains that when you feel you have lost everything and there are no solutions left, you should put the situation out of your hands and into God's hands, and ask for a miracle.`,
    speakerName: `Dubai Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=Latp0XujNXk`,
    videoTitle: `Asking Dubai Billionaires How They Got RICH!`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The most successful people have an unwavering belief in themselves. They know that even if they were to lose absolutely everything, they possess the mindset and skills to build it all back, often ten times bigger than before.`,
    speakerName: `Billionaires For a Living`,
    videoUrl: `https://www.youtube.com/watch?v=bPPc2coTClU`,
    videoTitle: `Meet The Kid Who Interviews Billionaires For a Living`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Utilize the "Augusta Rule" (IRC 280A) to rent out your primary residence for up to 14 days a year tax-free. Business owners with an S Corp can rent their home to their own business for these 14 days, creating a tax-free distribution for themselves while deducting the expense from their business.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=22CjsRG0sTc`,
    videoTitle: `He Made $7M/Year And Paid Zero Taxes!`,
    topic: `taxes`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you have a plan, write it down and figure it out. If someone else is already doing what you want to do, watch them, adapt their methods with your own unique flair, and always believe in yourself, as that belief will accelerate your journey to the top.`,
    speakerName: `SHAQ`,
    videoUrl: `https://www.youtube.com/watch?v=0I0EPRu3DJ0`,
    videoTitle: `Young Entrepreneur Interviews SHAQ`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Get a mentor. Definitely get a mentor because if you don't have a mentor, you don't have no direction. You don't find out his bad moves that he had made. You can grow from there.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=qQIKf7YQBbA`,
    videoTitle: `Asking Billionaires How They Got Rich! (Beverly Hills)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Nobody in the world has an excuse today to learn and win at the highest level because everyone has access to information to change their lives. Do not buy into the mindset that it's too hard because of your background or family situation; don't buy into any of that stuff.`,
    speakerName: `Patrick Bet-David`,
    videoUrl: `https://www.youtube.com/watch?v=ZX_BJKKyDXo`,
    videoTitle: `Young Entrepreneur Interviews Patrick Bet-David`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Mentorship is the only secret and shortcut to success in today's world. Learning directly from successful individuals is the best way to master fundamental business skills and build generational wealth.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=JKkwS6FT7wY`,
    videoTitle: `Asking Billionaires How They Got Rich! (New York)`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is to "invest by walking around," which the speaker compares to the "Peter Lynch model." He explains that you should observe what products the people around you are consistently buying and using—like Apple or Lululemon—and invest in those companies, adding that "it's not rocket science."`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=JMIE80d0Aoo`,
    videoTitle: `Asking Millionaires Who They're Voting For President`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Keep your head down, work hard, and have faith in God.`,
    speakerName: `San Francisco Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=G_GZbtj0uP8`,
    videoTitle: `Asking San Francisco Millionaires How They Got Rich!`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Believing that you can is way more profitable than believing that you can't.`,
    speakerName: `Houston Moguls`,
    videoUrl: `https://www.youtube.com/watch?v=HEgFl6N2u4M`,
    videoTitle: `Asking Houston Moguls How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Every success principle that I learn, the very first thing that I do is I go back and look at Scripture and see if it lines up. If it does, I'll follow it. If it doesn't, I ditch it.`,
    speakerName: `Wealthy Americans`,
    videoUrl: `https://www.youtube.com/watch?v=oDJEZ-n9TCM`,
    videoTitle: `Asking Wealthy Americans How They Got Rich! (Florida)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Never say never, as nothing in life—business, relationships, or health—is guaranteed. The only thing that is certain is your relationship with God, and if faith isn't your backbone, you have a long way to go.`,
    speakerName: `Las Vegas Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=D0utmFm1l0o`,
    videoTitle: `Asking Las Vegas Millionaires How They Got Rich!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you do those two things, stay away from vices and hang out with people that are destined to be successful, it is almost guaranteed that you will find a level of success.`,
    speakerName: `Miami Moguls`,
    videoUrl: `https://www.youtube.com/watch?v=PWVoNu4ytEA`,
    videoTitle: `Asking Miami Moguls How They Got Rich!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Start with a standard. What you accept, you can't change... Know your worth, know your value, and don't give freebies. You have to help people understand your value proposition.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=IUIG4YG0T-Q`,
    videoTitle: `Asking Billionaires How They Got Rich! (Houston)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Believe in yourself and just don't quit.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=d4Yuq3iP5eI`,
    videoTitle: `I Had to Beg Borrow & Steal.. Now I Make $300 Million`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given to overcome adversity in life and business is to practice daily gratitude, use morning mantras, meditate, and focus on just staying positive.`,
    speakerName: `Wealthy Americans`,
    videoUrl: `https://www.youtube.com/watch?v=O5R1z_gPCSo`,
    videoTitle: `Asking Wealthy Americans How They Got Rich! (Scottsdale)`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Observe the popular products, services, and brands that people are currently using and are loyal to. Find companies you genuinely love that have good people, processes, products, and profitability, and pursue those. Always do your homework and avoid looking for shortcuts or 'get rich quick' schemes.`,
    speakerName: `Wall Street Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=OtWKuR2hU68`,
    videoTitle: `I Asked Wall Street Millionaires How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `"When times are good, be the guy that stacks cash." Save your money during good economic times so that when tough times hit and people are forced to sell off their assets at a discount, you have the cash on hand to buy them.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=JsEUa3mMGe0`,
    videoTitle: `Asking Millionaires How They Got RICH! (Dallas)`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Focus on what you can control, get good mentorship, [and] don't worry about everything else flying around you. Everybody's got an opinion, and it's not near as bad as you think it is.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=9aBfrKtWJc8`,
    videoTitle: `I Was Bankrupt… Now I’ve Made $3 Billion`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Learn business early on, not to chase money or squeeze the system, but to understand how to provide good service and stay afloat so you can focus on your primary goal of helping others without financial worry.`,
    speakerName: `Billionaires`,
    videoUrl: `https://www.youtube.com/watch?v=PN9Z4QH8X2w`,
    videoTitle: `Asking Billionaires How They Got RICH!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You can tell the size of a man by the size of his problems. Get up every day, every time you get hit in the face. Have a relentless heart and there's nothing this world can stop you from doing.`,
    speakerName: `Justin Waller`,
    videoUrl: `https://www.youtube.com/watch?v=6lmwLam3f4k`,
    videoTitle: `Young Entrepreneur Interviews Millionaire Justin Waller`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You are owed nothing and your entitlement is going to keep you broke the rest of your life.`,
    speakerName: `Salt Lake City Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=90A-xjDipk4`,
    videoTitle: `Asking Salt Lake City Millionaires How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Either get there or die trying, but damn sure, don't be average. Never conform, never become civilized. Ever.`,
    speakerName: `Scottsdale Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=sExOe8q1QBc`,
    videoTitle: `Asking Scottsdale Millionaires How They Got Rich`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `We as men should model ourselves after Jesus Christ and what he did. He is the ultimate Adam.`,
    speakerName: `Supercar Owners`,
    videoUrl: `https://www.youtube.com/watch?v=n7FLA5IZkWA`,
    videoTitle: `Asking Supercar Owners How They Got RICH! (Florida)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you're going through hell, just keep on going. Because eventually you'll get out.`,
    speakerName: `Millionaire Golfers`,
    videoUrl: `https://www.youtube.com/watch?v=9FZ7chhIfUM`,
    videoTitle: `Asking Millionaire Golfers How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The interviewee reflects on the quote "More money, more problems," explaining that financial success brings unpredictable challenges, particularly that people around you change. He advises that you must learn to accept people for who they are, even if they cannot accept you for where you are at.`,
    speakerName: `Atlanta Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=2tRPK9s4p5k`,
    videoTitle: `Asking Atlanta Millionaires How They Got RICH!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't put being 'number one' on a pedestal. There is no embarrassment in not being number one, and you can still be highly successful as number two or three. Everything is great if you are true to who you actually are.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=PFvRtVvP-Bo`,
    videoTitle: `Asking Millionaires How They Got RICH! (New York City)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to scale your business. If you can't afford to buy property, start by renting, and as you find winning properties and scale up, your income will increase because it's ultimately a numbers game.`,
    speakerName: `Supercar Owners`,
    videoUrl: `https://www.youtube.com/watch?v=n3_QuKa208w`,
    videoTitle: `Asking Supercar Owners How They Got RICH! (Las Vegas)`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Consistency is the number one habit of highly successful people; by doing something every single day, your efforts compound to create exponential outcomes, meaning even "2 minutes a day is worth 2 hours on a Saturday."`,
    speakerName: `Californian Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=6WweLDK6oiY`,
    videoTitle: `I Asked Californian Millionaires How Much Money They LOST`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The biggest thing I want to sell people is belief in themselves... you can build the belief in yourself, but people don't want to work hard. The greatest thing for your self-image, by far, is work.`,
    speakerName: `Miami Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=ZFkKWGnm1PA`,
    videoTitle: `I Asked Miami Millionaires How They Got Rich`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be willing to make sacrifices, work hard, and avoid showing off. Prioritize honesty above all else and do not be afraid to reach out to others for help or networking.`,
    speakerName: `Luxury Shoppers`,
    videoUrl: `https://www.youtube.com/watch?v=ts5-LCzCUuE`,
    videoTitle: `Asking Luxury Shoppers How They Got RICH! (Dallas)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you're in doubt, do not doubt yourself. You have to build confidence by setting daily goals and keeping the promises you make to yourself; this discipline will ultimately lead you to achieve your biggest goals.`,
    speakerName: `Yacht Owners`,
    videoUrl: `https://www.youtube.com/watch?v=hRFCQAIa0gA`,
    videoTitle: `Asking Yacht Owners How They Got RICH!`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Ideas are cheap, execution is everything. It's not just taking the action, it's how you execute. It's the follow-through, it's the precision, it's the focus.`,
    speakerName: `Holiday Shoppers`,
    videoUrl: `https://www.youtube.com/watch?v=eSkosEaDnDw`,
    videoTitle: `Asking Holiday Shoppers How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `True wealth in the corporate world comes from equity, not just a salary. When you reach a point in your career where you can participate in equity programs, you should always take advantage of it and buy in as much as possible.`,
    speakerName: `Texas Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=exeXKslPiDI`,
    videoTitle: `Asking Texas Millionaires How They Got RICH!`,
    topic: `lifestyle`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Focus on two daily habits: achieving peak physical performance to maintain a positive mental state, and "being the source of what you seek" by serving others.`,
    speakerName: `Miami Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=BaxpJArMn9Y`,
    videoTitle: `Asking Miami Millionaires How to Get RICH!`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to understand and utilize your brain's "reticular activating system" by having big dreams and building self-worth. You must become obsessed with what you want, or your brain will filter out life-changing opportunities and you won't even see them when they appear.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=prPvzJwgHqg`,
    videoTitle: `How He Built A $200 Million/Year Security Company`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If anybody wanted to get rich, anyone, learn sales, learn leadership. And this market will reward you in ways you've never imagined if you've got good intentions and you like people.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=nReWQdfRSC8`,
    videoTitle: `Asking Millionaires How They Got RICH! (Scottsdale)`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `When you're young, you should put your eggs in one basket and just double down on your company or whatever it is, and try to grow that versus trying to diversify. Put in the long hours—even working 12 or 13 hours a day on the weekends—and you're going to be successful.`,
    speakerName: `Calabasas Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=kJ7HiO27n1g`,
    videoTitle: `Asking Calabasas Millionaires How They Got RICH!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `"If you don't come from a rich family, a rich family can come from you." The speaker emphasizes making the decision to be the one person who changes their family tree forever.`,
    speakerName: `Millionaire Homeowners`,
    videoUrl: `https://www.youtube.com/watch?v=_5yi6XW4Av8`,
    videoTitle: `Asking Millionaire Homeowners How They Got Rich`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `To build wealth, use 'trade lines' by becoming an authorized user on an older, high-limit credit card to boost your credit score. This allows you to access $50,000 to $100,000 in credit, which can be used to start and scale a business.`,
    speakerName: `Orlando Millionaire’s`,
    videoUrl: `https://www.youtube.com/watch?v=YU_58awAISY`,
    videoTitle: `Asking Orlando Millionaire’s How They Got RICH!`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Start a business and immediately reinvest your early profits into advertising, marketing, and branding. Building a strong brand identity is the most important factor for success, as it is how you become known to the public, regardless of your profession.`,
    speakerName: `Beverly Hills Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=xe3GmH-mBQI`,
    videoTitle: `Asking Beverly Hills Millionaires How They Got RICH!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Learn sales and never give up. Mastering the ins and outs of communicating with people through sales will make you successful anywhere, and as long as you don't quit when facing roadblocks, you can achieve whatever you want.`,
    speakerName: `A 27 Year Old`,
    videoUrl: `https://www.youtube.com/watch?v=V6I3R5Z-YZI`,
    videoTitle: `Asking A 27 Year Old How to Make $300 Million`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Stay sober in your twenties, surround yourself with like-minded people on the same mission, and respectfully distance yourself from those who aren't on your path. Most importantly, keep your body healthy; everything else can just happen.`,
    speakerName: `Supercar Owners`,
    videoUrl: `https://www.youtube.com/watch?v=G2kqG3kDdGo`,
    videoTitle: `Asking Supercar Owners How They Got RICH!`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be self-aware of what you are good at, and surround yourself with great people who are good at what you are not. No successful entrepreneur builds a business alone; if you want to win big, you need to have a great team around you.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=pBjoezYFA0Y`,
    videoTitle: `Asking Millionaires How They Got RICH! (Austin)`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't get caught up with the money. It's not about the money, it's about personal growth. Who you are as a person is way more important.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=3K43YBxUp0I`,
    videoTitle: `Meet The Most Interesting Man On The Planet`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `First you got to believe. Then figure out where you could add value... And then look for people who made it from the absolute bottom like you... Look for people who have done it and model those people.`,
    speakerName: `Luxury Shoppers`,
    videoUrl: `https://www.youtube.com/watch?v=ZHFNlM0xG4U`,
    videoTitle: `Asking Luxury Shoppers How They Got RICH! (Miami)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Do not focus on saving money or planning for retirement early on; instead, reinvest every penny into yourself, your business, and your brand to become better and faster. Only once you have built that foundation should you begin investing in other real assets.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=BP548td2dds`,
    videoTitle: `Asking Millionaires How They Got RICH! (Miami)`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Grant Cardone's final advice is that you are capable of achieving much more than you realize, and you should ignore the limiting beliefs of those who haven't accomplished anything themselves.`,
    speakerName: `Grant Cardone`,
    videoUrl: `https://www.youtube.com/watch?v=yOSsd1Tpno4`,
    videoTitle: `Young Entrepreneur Interviews Billionaire Grant Cardone`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is to focus on helping others succeed. By mentoring your team, providing constructive feedback, and lifting up the people around you, you ultimately create more opportunities for your own career growth.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=jJxwJhdKb1s`,
    videoTitle: `Asking Millionaires How They Got RICH! (Dallas)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you had to start over from $0, leverage your solid network to get initial capital, then start a simple service business (like short-form content or car detailing) to build up your funds. Once you have stacked up enough money, reinvest it into digital real estate.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=7Cxfg0N_MUw`,
    videoTitle: `From $0 To $12M A Year At 26Years Old. Here’s How`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't go for money, but think of money as a tool to do something great... If you focus on money and cars, you're never going to be happy, and if you're not happy, you're probably not going to have the drive and the passion you need to get there.`,
    speakerName: `Millionaire Homeowners`,
    videoUrl: `https://www.youtube.com/watch?v=H1Dt1Pz-B4g`,
    videoTitle: `Asking Millionaire Homeowners How They Got Rich`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Do as much research as you can across the board and do not wing it. Always set contingencies because unexpected costs will always arise, so do all the research you can possibly do.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=FLgy1LvYTDI`,
    videoTitle: `Asking Millionaires How They Got RICH! (Houston)`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Be completely honest with yourself about your flaws or bad habits, and then start with a very simple, positive action, such as deciding to smile and say hello to everyone. Achieving this small goal will make you feel better by the end of the day.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=bmQRL82f-5I`,
    videoTitle: `6 Questions With A Public CEO`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is that sales is a "transfer of certainty" where you must bridge the gap between a person's current situation and their desired outcome. To succeed, you must understand exactly who you are talking to, where they are starting from, and where they want to go.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=oRqUthcMi6I`,
    videoTitle: `The Single Skill That Built His $100M Year Business`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't talk about what you're going to do and just do it. Put your actions where your mouth is. Let the money come to you, don't chase it, because what's for you is going to be for you.`,
    speakerName: `Miami Luxury Shoppers`,
    videoUrl: `https://www.youtube.com/watch?v=efJj9j2NRJg`,
    videoTitle: `Asking Miami Luxury Shoppers How They Got Rich`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is that if you were to lose everything, the knowledge, contacts, and reputation you have built over your career will allow you to rebuild your empire. You should get right back into the field you are passionate about and know best.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=lAOliWexJgo`,
    videoTitle: `He Turned $100k Into $25M`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `"Don't count other people's money." Stop comparing yourself to what others have, especially since much of what you see on social media isn't real and will only make you feel insecure. Instead, worry about yourself and go at your own pace, and things will work out fine.`,
    speakerName: `Miami Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=O_FWBldliEo`,
    videoTitle: `Asking Miami Millionaires How They Got Rich`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Leverage AI as an assistant to facilitate and systematize your business. By using AI to speed up processes and make your work more efficient, you can simplify your workflow and focus your time and effort on getting more clients.`,
    speakerName: `Orlando Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=C2lgZOIPp8c`,
    videoTitle: `Asking Orlando Millionaires How They Got Rich`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The best decision I made in my lifetime was to major in engineering because it teaches you a lot about problem-solving and provides a foundation to pursue many different career paths beyond just engineering.`,
    speakerName: `Strangers`,
    videoUrl: `https://www.youtube.com/watch?v=1m7ERHu13sc`,
    videoTitle: `Asking Strangers How Much MONEY They Make (Austin, Texas)`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Find experts and mentors to guide you in areas where you lack expertise, as even experienced people get "rusty" and need someone to help steer them back on the right path.`,
    speakerName: `A Tech Millionaire`,
    videoUrl: `https://www.youtube.com/watch?v=3G79t-mcgJ8`,
    videoTitle: `Asking A Tech Millionaire How To Start & Scale a Tech Company`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Focus on building reoccurring revenue because it shifts the focus to the lifetime value of a customer, allowing a business to outspend its competition on customer acquisition even if it means taking an initial loss.`,
    speakerName: `Denver Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=w1bpdHouHpI`,
    videoTitle: `Asking Denver Millionaires How Much Money They Make`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The number one skill needed to be successful in the business world is the ability to sell yourself. If you can sell yourself, it doesn't matter what industry you are in, but if you cannot sell yourself, you will not be successful anywhere.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=Kq4nx8DLrpY`,
    videoTitle: `Asking Millionaires How They Got RICH! (Houston)`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The secret to marketing is staying laser-focused on the problem you are trying to solve and defining the story you want to tell. Do not worry about your website or content until that story is completely nailed down and fully embraced by everyone in your organization.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=MtvcqGNGev8`,
    videoTitle: `Entrepreneurs Guide To Start and Scale ANY Business`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Information is gold.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=3aG9DVb6vBs`,
    videoTitle: `How to Make $2 Million in Commercial Real Estate`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Get your LLC going, learn how to get the vehicles in your LLC, and start building up business credit.`,
    speakerName: `Entrepreneurs`,
    videoUrl: `https://www.youtube.com/watch?v=Iw7huxwfHRM`,
    videoTitle: `Asking Entrepreneurs How They Got RICH! (San Antonio)`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Believing in growth is the top priority; you must constantly look forward without fear, making bold investments in equipment and personnel while outsourcing secondary tasks to focus on the core business.`,
    speakerName: `Golf Course Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=RGt99we0cGA`,
    videoTitle: `Asking Golf Course Millionaires How They Got Rich`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given in the video is to "take the pathetic next best step." Instead of overthinking the big things, you should find a tiny, necessary task and execute it with confidence, being proud that you got it done.`,
    speakerName: `Josh Terry`,
    videoUrl: `https://www.youtube.com/watch?v=_wo0ox2mSjc`,
    videoTitle: `HOW TO GET EVERYTHING YOU WANT IN LIFE Ft. Josh Terry`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The speaker advises having faith in yourself and in something bigger than yourself—whether you call it God, the universe, or nature—and believing that this greater force will provide what you need to achieve your goals.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=e38FC689mXA`,
    videoTitle: `5 SKILLS Every Young Man Should Know in 2023`,
    topic: `faith`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is to "Just stick to one method and perfect it. Don't jump around." You have to figure out what strategy works best for you and stay consistent with it through the learning curve.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=ml6tMccO2xE`,
    videoTitle: `How to Wholesale Real Estate for Beginners`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Make sure you find and have your own "why," as having a clear purpose or underlying motivation is the most important factor for staying consistent and successful in your endeavors.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=__CY9eanfV4`,
    videoTitle: `School of Hard Knocks First Speaking Event!`,
    topic: `education`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you're bored and you want to have unlimited income potential and joy in your job, track me down.`,
    speakerName: `a Private Equity Millionaire`,
    videoUrl: `https://www.youtube.com/watch?v=uf0Or7n8_bU`,
    videoTitle: `Asking a Private Equity Millionaire How He Got Rich`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `You can always find a way to put money aside; without financial stability, you lose optionality.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=O_pe_5L769E`,
    videoTitle: `Asking Millionaires How To Make $1,000,000!`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is that as a leader, it is your responsibility to recognize when your employees are overwhelmed and to "stop handing them balls." In some cases, you must actively reduce their workload—or "take them down the mountain"—to prevent them from dropping everything and failing.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=8GgL-uvICKY`,
    videoTitle: `From Summit to Success: Entrepreneur's Billion-Dollar Lesson from 'Into Thin Air`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to avoid procrastination because time is our only non-renewable resource. The speaker emphasizes the concept of "failing fast"—if you want to start a business, get in there and try it; if you fail, get it out of the way quickly so you can learn from it and move on to the next idea.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=MQv7Te8VmYI`,
    videoTitle: `How I Turned $1,000 Into $1 Billion`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Stick to what you know, or learn something and learn really deep on it. If you find something that you're passionate about, go really deep in it and learn that. You're going to be way more successful by sticking to one thing, going deep in it, and understanding the players there.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=BT6YGOROV6c`,
    videoTitle: `Life After Selling Your Company For $1 Billion`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final lesson shared in the video is to find a strong, personal "why" to motivate yourself, such as being able to take care of your family and make a positive impact on others. He also advises chasing your full human potential to become multi-faceted, rather than just limiting yourself to being a "business guy."`,
    speakerName: `Robert Miller`,
    videoUrl: `https://www.youtube.com/watch?v=TpVlJpiV6U8`,
    videoTitle: `10 Questions with a Millionaire: Founder & E-commerce Entrepreneur Robert Miller`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `I would tell myself to get more involved with other people on campus. I mean you have to learn to be an adult.`,
    speakerName: `Texan’s`,
    videoUrl: `https://www.youtube.com/watch?v=8M5QEOicQKQ`,
    videoTitle: `Asking Texan’s Their Best Life Advice (DALLAS!)`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Avoid "can't miss" investments, as they are usually too good to be true and will lead you off track. Instead, stay focused on your plan.`,
    speakerName: `Former Nike President`,
    videoUrl: `https://www.youtube.com/watch?v=1NvSd_heJxE`,
    videoTitle: `Exclusive Interview with Former Nike President: Life Lessons and Advice for Success`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Always keep learning and investing in courses, because if you think you know it all, you've already lost. Build an internal library of resources and courses that you can draw from whenever you encounter business problems you don't know how to solve.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=JiF92PVjOZc`,
    videoTitle: `Day in the Life of a 25 Year Old Millionaire`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Sacrifice whatever it takes for your dream, and believe that anything is possible. The moment you stop letting outside voices dictate what you can or cannot do, and start being true to yourself and 100% accountable, you can make anything you want a reality.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=pTifbfUnsH8`,
    videoTitle: `From Minimum Wage to Real Estate Millionaire`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Take more risk and worry less about the immediate and what people think about you and what you say and what you do. And follow your heart.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=Q0cgOMI5gn0`,
    videoTitle: `I Asked Texan Millionaires Their Best Financial Decision`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given in the video is: "Closers ask hard questions." The speaker explains that salespeople shouldn't be afraid to ask difficult or awkward questions—such as inquiring about a prospect's finances or the consequences of not solving their problem—because being willing to have these hard conversations is essential for achieving success in sales.`,
    speakerName: `Alex Hormozi`,
    videoUrl: `https://www.youtube.com/watch?v=N_KjHR6cKC8`,
    videoTitle: `5 Sales Tips To Start Closing Deals Ft: Alex Hormozi’s Closer Jacob Hopkins`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `I'm a big believer that you got to have goals in life. If you don't have any kind of goal, you can't be happy; you need something that you're pushing towards and making progress to.`,
    speakerName: `Tips for Building Wealth and Success`,
    videoUrl: `https://www.youtube.com/watch?v=cttsP_8MjEo`,
    videoTitle: `10 Questions with a Real Estate Millionaire: Tips for Building Wealth and Success`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Sometimes you gotta jump out of a plane and build the parachute on the way down. Surround yourself with people who are smarter than you, and if some old dog is offering their time to you, take it.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=6zKF1LZFn8Q`,
    videoTitle: `Here’s How Real Estate Millionaires Spend Their Day`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is that people who have a backup plan or a safety net rarely succeed, whereas someone who has no other choice but to make it work will always find a way to succeed.`,
    speakerName: `Grant Mitt`,
    videoUrl: `https://www.youtube.com/watch?v=AvKXrCCUEMI`,
    videoTitle: `10 Questions with a Millionaire: Founder & Investor Grant Mitt`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Focus on asking what you can do to help others rather than just how to get ahead. By looking for opportunities to lift others up, you will find that people are more likely to lift you up in return.`,
    speakerName: `Doug Williams`,
    videoUrl: `https://www.youtube.com/watch?v=VNtZfU84euk`,
    videoTitle: `10 Questions with a Millionaire: Investor & Executive Doug Williams`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't go to school during the summer. Go get jobs about things you think you might be interested in. So that by the time you're out of college you've worked 3 or 4 different jobs.`,
    speakerName: `Millionaires`,
    videoUrl: `https://www.youtube.com/watch?v=67T9EMIvOlA`,
    videoTitle: `Asking Millionaires What They Are Investing in`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you can't manage a thousand dollars, then you can't manage a million dollars. So learn to manage that thousand that you have.`,
    speakerName: `Lavon Perrin`,
    videoUrl: `https://www.youtube.com/watch?v=vzDYSrzISzo`,
    videoTitle: `10 Questions with a Millionaire: Insurance CEO Lavon Perrin`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The impact you make on others is going to determine how successful you are.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=jR6g__ogNkc`,
    videoTitle: `These Millionaires Gave Us Life Changing Advice...`,
    topic: `wealth`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Don't just view Squid Game as a crazy, successful TV show. Instead, analyze it deeply to extract the lessons and strategies it used, and apply those insights to your own real life and business to achieve similar success.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=37qvYddjCBc`,
    videoTitle: `How Squid Game Broke Netflix`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The speaker suggests that if Twitter implements an edit button, they should use a system like blockchain technology to keep a transparent backlog of all changes. This would allow users to track original versus edited versions of a tweet, thereby maintaining the integrity and authenticity of the platform's content.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=nsxlR1fi_tk`,
    videoTitle: `5 things Elon Musk could change about Twitter`,
    topic: `content-creation`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Prioritize spending time with family and close friends. Making time every week to connect with them is crucial because they are the people who will support you through your darkest moments and celebrate your wins.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=0ccWUHrUREo`,
    videoTitle: `How balance leads to productivity`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `If you have strong sales and interpersonal relationship skills, becoming a remote sales representative is a great way to make money remotely on your own.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=Y3brjwOs3gA`,
    videoTitle: `7 Ways to Make a Full Time Income Traveling The World`,
    topic: `sales`,
    source: `School of Hard Knocks`,
  },
  {
    text: `It is incredibly important to take the earnings you make from your primary success—the thing you do best—and invest them to grow your overall portfolio.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=mQenPbfmECk`,
    videoTitle: `Your favorite rapper didn’t get rich off music`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to "lawyer up" when entering a business partnership or signing documents related to ownership. You must put friendships aside and hire a lawyer to protect yourself and ensure you don't sign something that could lead to your downfall.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=lvAYo3DBBxU`,
    videoTitle: `Top 5 Takeaways from “The social network”`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `To build self-confidence, identify the root cause of your insecurity, assess your situation, and cut out toxic or unsupportive people from your life. Then, create and follow an actionable plan to become the confident person you want to be.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=MRIJjEbJS7s`,
    videoTitle: `How to build self confidence`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Creating quality content and scaling on social media is one of the most valuable skills in today's world that can be carried with you for the rest of your life. Mastering this expertise allows you to cut through the noise, opening doors to new opportunities and supplemental income.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=81dWG1gor4I`,
    videoTitle: `Why You Need To Start Creating Content`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice highlights the shift toward decentralization in the music industry, noting that artists are increasingly taking back their rights by using exclusive platforms. This trend suggests that dedicated fans will likely follow and support artists on these individual platforms to access their work and hear what they have to say.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=Ize5BerUM74`,
    videoTitle: `How Kanye is Transforming The Music Industry`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to consider becoming an elevator repairman. The speaker suggests that if you are looking to try something new, it is a lucrative and hands-on career worth checking out.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=M_x3Sl-Hlw4`,
    videoTitle: `7 High Paying Jobs That Don’t require a degree`,
    topic: `education`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to follow the investment moves of successful crypto leaders like Marc Andreessen by looking into NFT projects that accept direct company investors and considering stocking up on NFTs from projects receiving heavy outside investments.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=ypEYnZ8bTec`,
    videoTitle: `The Father of Crypto Is Investing In This…`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given in the video is to "let your money work for you." Instead of leaving your money sitting in a bank where it loses value over time due to inflation, you should invest it into appreciating assets like real estate, stocks, or cryptocurrency so that it can grow.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=h85y36g5vP8`,
    videoTitle: `5 Lessons I learned from talking with Multi-Millionaires`,
    topic: `real-estate`,
    source: `School of Hard Knocks`,
  },
  {
    text: `At the end of the day, you need to walk your own path. You have one life to live, so you must be the ultimate decision-maker in your life and not let others dictate your choices.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=Kx_pzUJ4OxA`,
    videoTitle: `5 Lessons I Wish I Knew in High School`,
    topic: `education`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Expand the reach of your online course beyond your existing audience by uploading it to platforms like Udemy and Skillshare. This allows you to access a much larger pool of potential buyers rather than relying solely on your own followers.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=1SzDCdlUPCc`,
    videoTitle: `5 Profitable Online Business Ideas 2022`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to promote engagement through your post and video descriptions by asking thought-provoking questions, conversation starters, or calls to action to encourage comments and discussions.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=yQfItKAlNIM`,
    videoTitle: `How To Grow FAST On Instagram and Facebook | Social Media Strategy`,
    topic: `content-creation`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Whether you have a degree or not, success ultimately comes down to your own personal hard work and drive. Without those two qualities, you will not be able to achieve the things you want in life.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=lAnIOo7qPAQ`,
    videoTitle: `SHOULD I GO TO COLLEGE? Getting A College Degree vs. Not Getting A College Degree Debate in 2021`,
    topic: `education`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Ultimately, Reels should just be one part of your brand strategy to build overall awareness around your brand.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=pBzmIEVpSiI`,
    videoTitle: `How To Upload Facebook Reels | Grow Your FB Page RAPIDLY`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to surround yourself with a supportive and collaborative community that champions fellow entrepreneurs and small businesses. This type of environment is essential to starting up and truly thriving as a business owner.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=InwiIbuE3WQ`,
    videoTitle: `Top 5 Cities to become an Entrepreneur in 2021! Perfect for aspiring entrepreneurs.`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to network by investing in other people's stories and offering free value, rather than just trying to sell your own products. By building these genuine relationships, people are more likely to remember you and refer you in the future, allowing your business to grow passively over time.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=DkwsSB-B12Q`,
    videoTitle: `5 BEST Tips For Beginner Entrepreneurs | Understanding Business Basics`,
    topic: `investing`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Dedicate at least one hour every single day to working on your business, regardless of how busy you are with school or work. Maintaining this consistent daily momentum is what leads to massive growth, while skipping days will stall your progress.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=REfO4L4mxO0`,
    videoTitle: `USE THIS TO QUIT YOUR JOB | 5 Productivity Hacks for Entrepreneurs who are Working or are in College`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice given is that while budgeting is essential, eventually "one of the best answers to actually fixing your financial problems is actually to just increase your income level."`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=ky5Y75IqQE0`,
    videoTitle: `BEST Budgeting Apps 2021 | How to Budget for Beginners`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `To expand your income, get creative with pet care services by offering bundled walk times of varying lengths and providing additional services like cleaning, showering, and playtime.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=EiI3ja6BCYs`,
    videoTitle: `5 BEST Businesses For Teens in 2021 with Low/No Startup Cost`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to "never get discouraged when you're posting." You should ignore negative opinions from others, block out people who say your content is weird or corny, and focus on doing what makes you passionate and happy.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=o7Fk4D0ZnN8`,
    videoTitle: `How To BLOW Up On TikTok From A Verified Creator`,
    topic: `content-creation`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The simplest way to improve your credit score is to avoid late payments at all costs. To help achieve this, set up automatic transfers from your checking account to pay off your credit card, or put your monthly bills on your credit card to ensure they are consistently paid off on time.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=VcQ1ZTc0aIo`,
    videoTitle: `How to Improve Your Credit Score | Understanding Credit Cards`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to find a passion project you love—like a business, blog, or content channel—and dedicate a little time to it every single day. Having something you are excited to work on can spark motivation and boost your mental health, even when other areas of your life are challenging.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=HI-v-rWH7X4`,
    videoTitle: `How to Improve Your Mental Health | 5 Ways to BOOST Your Mental Health`,
    topic: `mindset`,
    source: `School of Hard Knocks`,
  },
  {
    text: `Surround yourself with "Good Listeners & Advice Givers"—people who listen more than they speak, allow you to vent, and provide constructive advice to help you navigate challenges.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=jG_Y8OOOXDY`,
    videoTitle: `How to Have an ELITE INNER CIRCLE | 10 Qualities You Want In Your Inner Circle`,
    topic: `success`,
    source: `School of Hard Knocks`,
  },
  {
    text: `The final piece of advice is to offer graphic design services online, leveraging skills in software like Photoshop to find clients from anywhere, including small businesses and brands. This allows you to market yourself globally and perform design work for companies that need those specific services.`,
    speakerName: `School of Hard Knocks`,
    videoUrl: `https://www.youtube.com/watch?v=1qEw8vKwyO0`,
    videoTitle: `5 Ways to Make $1000 as a TEEN | How to make $1000 Fast 💰`,
    topic: `entrepreneurship`,
    source: `School of Hard Knocks`,
  },
];

// Total: 169 quotes